// MAIN STATE
EXTERNAL GET_CURRENT_DAY()
EXTERNAL GET_MY_NAME()
EXTERNAL GET_MY_EMAIL()

// DAY ONE
EXTERNAL GET_DAY_ONE_DREAM()
EXTERNAL GET_DAY_ONE_SAW_EMAIL_BEFORE_LOG()

// DAY TWO
EXTERNAL GET_DAY_TWO_DREAM()
EXTERNAL GET_DAY_TWO_SAW_EMAIL_BEFORE_LOG()

// DAY THREE
EXTERNAL GET_DAY_THREE_DREAM()