EXTERNAL GET_VAR_VALUE(var_name)

CONST CURRENT_DAY = "CURRENT_DAY"
CONST MY_EMAIL = "MY_EMAIL"
CONST MY_NAME = "MY_NAME"
CONST DAY_ONE_DREAM = "DAY_ONE_DREAM"
CONST DAY_ONE_SAW_EMAIL_BEFORE_LOG = "GET_DAY_ONE_SAW_EMAIL_BEFORE_LOG"
CONST DAY_TWO_DREAM = "DAY_TWO_DREAM"
CONST DAY_TWO_SAW_EMAIL_BEFORE_LOG = "DAY_TWO_SAY_EMAIL_BEFORE_LOG"